### ISSUE TITLE
Clone and git is not helping me use the source code

### ISSUE THREAD

**Issue by Giova3d** [unbolt/WeiWuWei#5]
Can I get an explanation to how I can make a successful launcher from the source code I get from epic games for the unreal 4 engine. 

I think my problem is that I'm just downloading and never placing files and folders where they need to be... but I can never get a successful compile in visual studio.

**Comment by Giova3d** [comment]
Can I get an explanation to how I can make a successful launcher from the source code I get from epic games for the unreal 4 engine. 


I think my problem is that I'm just downloading and never placing files and folders where they need to be... but I can never get a successful compile in visual studio.

**Comment by unbolt** [comment]
Where exactly do you think you're asking this question? Cos fairly sure this isn't where you want to be.
